import { NextRequest, NextResponse } from 'next/server';
import { authenticateRequest } from '@/lib/api/auth';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

interface ReportData {
  searcherName: string;
  searcherEmail: string;
  period: string;
  metrics: {
    dealsPassed: number;
    dealsMovedToIoi: number;
    cimsProceeding: number;
    dealsInPipeline: number;
    totalPipelineValue: number;
    cimsWithRedFlags: number;
    cimsWithGreenFlags: number;
    topRedFlags: Array<{ flag: string; count: number }>;
    topGreenFlags: Array<{ flag: string; count: number }>;
    conversionRates: {
      cimToIoi: number;
      ioiToLoi: number;
      loiToClose: number;
    };
  };
}

async function generateReportHTML(data: ReportData, isBulk: boolean, searchers?: ReportData[]): Promise<string> {
  const formatCurrency = (value: number) => {
    if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
    if (value >= 1000) return `$${(value / 1000).toFixed(1)}K`;
    return `$${value.toFixed(0)}`;
  };

  if (isBulk && searchers) {
    // Bulk report
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Investor Report - ${data.period}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; }
    h1 { color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
    h2 { color: #334155; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background-color: #f1f5f9; font-weight: 600; }
    .metric-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 15px 0; }
    .red-flag { color: #dc2626; }
    .green-flag { color: #059669; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <h1>Investor Portfolio Report - ${data.period}</h1>
  <p>Generated: ${new Date().toLocaleString()}</p>
  
  <h2>Portfolio Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Searcher</th>
        <th>Deals Passed</th>
        <th>Moved to IOI</th>
        <th>CIMs Proceeding</th>
        <th>Pipeline Value</th>
        <th>CIM → IOI Rate</th>
      </tr>
    </thead>
    <tbody>
      ${searchers.map(s => `
        <tr>
          <td>${s.searcherName}</td>
          <td>${s.metrics.dealsPassed}</td>
          <td>${s.metrics.dealsMovedToIoi}</td>
          <td>${s.metrics.cimsProceeding}</td>
          <td>${formatCurrency(s.metrics.totalPipelineValue)}</td>
          <td>${s.metrics.conversionRates.cimToIoi.toFixed(1)}%</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  ${searchers.map((searcher, idx) => `
    <h2>${searcher.searcherName} - Detailed Metrics</h2>
    <div class="metric-card">
      <strong>Deals Passed:</strong> ${searcher.metrics.dealsPassed}<br>
      <strong>Moved to IOI:</strong> ${searcher.metrics.dealsMovedToIoi}<br>
      <strong>CIMs Proceeding:</strong> ${searcher.metrics.cimsProceeding}<br>
      <strong>Pipeline Value:</strong> ${formatCurrency(searcher.metrics.totalPipelineValue)}<br>
      <strong>Deals in Pipeline:</strong> ${searcher.metrics.dealsInPipeline}
    </div>
    
    ${searcher.metrics.topRedFlags.length > 0 ? `
      <h3>Top Red Flags</h3>
      <ul>
        ${searcher.metrics.topRedFlags.map(f => `<li class="red-flag">${f.flag} (${f.count} CIMs)</li>`).join('')}
      </ul>
    ` : ''}
    
    ${searcher.metrics.topGreenFlags.length > 0 ? `
      <h3>Top Green Flags</h3>
      <ul>
        ${searcher.metrics.topGreenFlags.map(f => `<li class="green-flag">${f.flag} (${f.count} CIMs)</li>`).join('')}
      </ul>
    ` : ''}
  `).join('')}
  
  <div class="footer">
    <p>Report generated by SearchFindr Investor Dashboard</p>
  </div>
</body>
</html>
    `;
  }

  // Single searcher report
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${data.searcherName} - ${data.period} Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; }
    h1 { color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
    h2 { color: #334155; margin-top: 30px; }
    .metric-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 15px 0; display: inline-block; width: 30%; margin-right: 2%; }
    .red-flag { color: #dc2626; margin: 8px 0; }
    .green-flag { color: #059669; margin: 8px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; color: #64748b; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background-color: #f1f5f9; font-weight: 600; }
  </style>
</head>
<body>
  <h1>${data.searcherName} - ${data.period} Report</h1>
  <p><strong>Email:</strong> ${data.searcherEmail}</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  
  <h2>Key Metrics</h2>
  <div class="metric-card">
    <strong>Deals Passed</strong><br>
    <span style="font-size: 24px; font-weight: bold;">${data.metrics.dealsPassed}</span>
  </div>
  <div class="metric-card">
    <strong>Moved to IOI</strong><br>
    <span style="font-size: 24px; font-weight: bold;">${data.metrics.dealsMovedToIoi}</span>
  </div>
  <div class="metric-card">
    <strong>CIMs Proceeding</strong><br>
    <span style="font-size: 24px; font-weight: bold;">${data.metrics.cimsProceeding}</span>
  </div>
  
  <div class="metric-card">
    <strong>Pipeline Value</strong><br>
    <span style="font-size: 24px; font-weight: bold;">${formatCurrency(data.metrics.totalPipelineValue)}</span>
  </div>
  <div class="metric-card">
    <strong>Deals in Pipeline</strong><br>
    <span style="font-size: 24px; font-weight: bold;">${data.metrics.dealsInPipeline}</span>
  </div>
  <div class="metric-card">
    <strong>CIMs with Red Flags</strong><br>
    <span style="font-size: 24px; font-weight: bold; color: #dc2626;">${data.metrics.cimsWithRedFlags}</span>
  </div>
  
  <h2>Conversion Rates</h2>
  <table>
    <tr>
      <th>Metric</th>
      <th>Rate</th>
    </tr>
    <tr>
      <td>CIM → IOI</td>
      <td>${data.metrics.conversionRates.cimToIoi.toFixed(1)}%</td>
    </tr>
    <tr>
      <td>IOI → LOI</td>
      <td>${data.metrics.conversionRates.ioiToLoi.toFixed(1)}%</td>
    </tr>
    <tr>
      <td>LOI → Close</td>
      <td>${data.metrics.conversionRates.loiToClose.toFixed(1)}%</td>
    </tr>
  </table>
  
  ${data.metrics.topRedFlags.length > 0 ? `
    <h2>Top Red Flags</h2>
    <ul>
      ${data.metrics.topRedFlags.map(f => `<li class="red-flag"><strong>${f.flag}</strong> - Found in ${f.count} CIMs</li>`).join('')}
    </ul>
  ` : ''}
  
  ${data.metrics.topGreenFlags.length > 0 ? `
    <h2>Top Green Flags</h2>
    <ul>
      ${data.metrics.topGreenFlags.map(f => `<li class="green-flag"><strong>${f.flag}</strong> - Found in ${f.count} CIMs</li>`).join('')}
    </ul>
  ` : ''}
  
  <div class="footer">
    <p>Report generated by SearchFindr Investor Dashboard</p>
  </div>
</body>
</html>
  `;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ type: string }> }
) {
  try {
    const { type } = await params;
    if (type !== 'weekly' && type !== 'monthly') {
      return NextResponse.json({ error: 'Invalid report type. Use "weekly" or "monthly"' }, { status: 400 });
    }

    const { supabase, user } = await authenticateRequest(req);

    // Check if user has investor role
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!profile || profile.role !== 'investor') {
      return NextResponse.json({ error: 'Access denied. Investor role required.' }, { status: 403 });
    }

    const searcherId = req.nextUrl.searchParams.get('searcherId');
    const workspaceId = req.nextUrl.searchParams.get('workspaceId');
    const bulk = req.nextUrl.searchParams.get('bulk') === 'true';

    // Use service role
    const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      return NextResponse.json({ error: 'Service configuration error' }, { status: 500 });
    }

    const supabaseAdmin = createSupabaseClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: { persistSession: false },
    });

    // Calculate period
    const now = new Date();
    let periodStart: Date;
    let periodEnd: Date = now;
    let periodLabel: string;

    if (type === 'weekly') {
      periodStart = new Date(now);
      periodStart.setDate(now.getDate() - 7);
      periodLabel = `Week of ${periodStart.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${periodEnd.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
    } else {
      periodStart = new Date(now.getFullYear(), now.getMonth(), 1);
      periodLabel = `${now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`;
    }

    if (bulk || !searcherId) {
      // Generate bulk report for all searchers
      const { data: links } = await supabase
        .from('investor_searcher_links')
        .select('*')
        .eq('investor_id', user.id);

      if (!links || links.length === 0) {
        return NextResponse.json({ error: 'No searchers linked' }, { status: 404 });
      }

      // Fetch details for each searcher (simplified - in production, you'd want to optimize this)
      const searchersData: ReportData[] = [];
      
      for (const link of links) {
        // Fetch searcher details (simplified version - reuse logic from details endpoint)
        // For now, return a basic structure
        const searcherData: ReportData = {
          searcherName: link.custom_display_name || `Searcher ${link.searcher_id.slice(0, 8)}`,
          searcherEmail: '',
          period: periodLabel,
          metrics: {
            dealsPassed: 0,
            dealsMovedToIoi: 0,
            cimsProceeding: 0,
            dealsInPipeline: 0,
            totalPipelineValue: 0,
            cimsWithRedFlags: 0,
            cimsWithGreenFlags: 0,
            topRedFlags: [],
            topGreenFlags: [],
            conversionRates: {
              cimToIoi: 0,
              ioiToLoi: 0,
              loiToClose: 0,
            },
          },
        };
        searchersData.push(searcherData);
      }

      const html = await generateReportHTML(searchersData[0] || {
        searcherName: 'Portfolio',
        searcherEmail: '',
        period: periodLabel,
        metrics: {
          dealsPassed: 0,
          dealsMovedToIoi: 0,
          cimsProceeding: 0,
          dealsInPipeline: 0,
          totalPipelineValue: 0,
          cimsWithRedFlags: 0,
          cimsWithGreenFlags: 0,
          topRedFlags: [],
          topGreenFlags: [],
          conversionRates: { cimToIoi: 0, ioiToLoi: 0, loiToClose: 0 },
        },
      }, true, searchersData);

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="investor-${type}-report-${Date.now()}.html"`,
        },
      });
    } else {
      // Single searcher report
      if (!workspaceId) {
        return NextResponse.json({ error: 'workspaceId required for single searcher report' }, { status: 400 });
      }

      // Fetch searcher details using the same logic as details endpoint
      // For now, return a simplified version
      const reportData: ReportData = {
        searcherName: 'Searcher',
        searcherEmail: '',
        period: periodLabel,
        metrics: {
          dealsPassed: 0,
          dealsMovedToIoi: 0,
          cimsProceeding: 0,
          dealsInPipeline: 0,
          totalPipelineValue: 0,
          cimsWithRedFlags: 0,
          cimsWithGreenFlags: 0,
          topRedFlags: [],
          topGreenFlags: [],
          conversionRates: {
            cimToIoi: 0,
            ioiToLoi: 0,
            loiToClose: 0,
          },
        },
      };

      const html = await generateReportHTML(reportData, false);

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="${reportData.searcherName}-${type}-report-${Date.now()}.html"`,
        },
      });
    }
  } catch (error) {
    console.error('Error generating report:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to generate report';
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
